name: Amplify Docker Images (CD) Deploy 2.3

on: [workflow_dispatch]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
          key: ${{ secrets.AWS_ACCESS_KEY_ID_SB }}
          name: id_rsa
          known_hosts: ${{ secrets.INSTANCE_ID_SB }}
    - name: rsync over ssh
      run: ./deploy_to_aws.sh
