name: Amplify Docker Images (CD) Deploy 2.3

on: [workflow_dispatch]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: deploy file
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        username: 'ec2-user'
        server: ${{ secrets.KNOWN_HOSTS }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
    
     
